language: java
jdk:
- openjdk12

sudo: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

addons:
  sonarcloud:
    organization: "euiagosilva"
    token:
      secure: "e454cc8a465e35d5ade734d9b9619526f04b6c87"

script:
  - ./gradlew sonarqube