version: '3.5'

services:
  car-graphql-db:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres/car-graphql-db/data:/var/lib/postgresql/data
    container_name: car-graphql-db
    environment:
      POSTGRES_DB: car_graphql_db
      POSTGRES_PASSWORD: secret
